home-assistant:
  replicaCount: 1
  controller:
    type: StatefulSet
  persistence:
    enabled:
    accessMode: ReadWriteOnce
    size: 2Gi
    existingVolume: "home-assistant-pv"
  additionalPorts:
    - name: dlna
      containerPort: 5555
      protocol: TCP
  additionalServices:
    - name: dlna
      port: 5555
      targetPort: dlna
      type: ClusterIP
      protocol: TCP
  serviceMonitor:
    enabled: true
    namespace: prometheus
    scrapeInterval: 30s
    labels:
      release: prometheus
