apiVersion: v1
kind: PersistentVolume
metadata:
  name: dind-directory-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/mnt/dind
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist

