apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/mnt/home-assistant-data
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist

