cloudflare-tunnel:
  account: e05d0d280d6d4bc63f73d1a72a0c5987
  tunnelName: skynet.intranet
  secretName: cloudflare-tunnel-secret
  enableWarp: false
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    "node-role.kubernetes.io/control-plane": ""
