traefik:
  env:
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: token
  service:
    enabled: true
    type: ClusterIP
  ports:
    web:
      port: 80 # This changes the --entrypoints.web.address=:8000 to :80
      hostPort: 80 # This binds the Host Node port 80 to the Container port 80
      exposedPort: 80 # This updates the K8s Service object
      protocol: TCP
    websecure:
      port: 443 # This changes the --entrypoints.websecure.address=:8443 to :443
      hostPort: 443 # This binds the Host Node port 443 to the Container port 443
      exposedPort: 443 # This updates the K8s Service object
      protocol: TCP
  hostNetwork: true
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.cavaleiro.in`)
      entryPoints:
        - web
  securityContext:
    capabilities:
      add:
        - NET_BIND_SERVICE
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    runAsGroup: 65532
    runAsNonRoot: false
    runAsUser: 0
  providers:
    kubernetesCRD:
      allowExternalNameServices: true
      allowCrossNamespace: true
    kubernetesIngress:
      allowExternalNameServices: true
    kubernetesGateway:
      enabled: false
  persistence:
    enabled: true
    name: data
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 128Mi
    path: /data
  additionalArguments:
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    - "--certificatesresolvers.cloudflare.acme.email=clayton@xdevel.com.br"
    - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
