gha-runner-scale-set:
  ## URL do repositório ou organização
  githubConfigUrl: "https://github.com/catdevsecops"

  ## Nome da Secret gerada pelo seu ExternalSecret
  githubConfigSecret: "github-app-secret"

  ## Configuração do Runner
  minRunners: 0
  maxRunners: 3

  ## Se você for usar Docker dentro dos runners (build de imagens)
  containerMode:
    # No Bare Metal, usamos emptyDir para não depender de StorageClasses
    type: "kubernetes"
    kubernetesModeWorkVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"

  ## Configuração do Controller
  controllerServiceAccount:
    name: arc-systems-arc-operator-gha-rs-controller
    namespace: arc-systems

  ## Nome do Runner Group no GitHub (opcional)
  runnerScaleSetName: "k8s-runner-set"

  # Garante que o pod do runner use uma ServiceAccount específica
  template:
    spec:
      serviceAccountName: "arc-runner-admin-sa"
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          securityContext:
            runAsUser: 1001
            fsGroup: 1001
