gha-runner-scale-set:
  ## URL do repositório ou organização
  githubConfigUrl: "https://github.com/catdevsecops/home-automated-infrastructure"

  ## Nome da Secret gerada pelo seu ExternalSecret
  githubConfigSecret: "github-app-secret"

  ## Configuração do Runner
  minRunners: 1
  maxRunners: 3

  ## Configuração do Controller
  controllerServiceAccount:
    name: arc-systems-arc-operator-gha-rs-controller
    namespace: arc-systems

  ## Nome do Runner Group no GitHub (opcional)
  runnerScaleSetName: "k8s-runner-set"
  template:
    spec:
      initContainers:
        - name: init-dind-externals
          image: ghcr.io/actions/actions-runner:latest
          command:
            ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///var/run/docker.sock
            - --group=$(DOCKER_GROUP_GID)
            - --mtu=1300
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          restartPolicy: Always
          startupProbe:
            exec:
              command:
                - docker
                - info
            initialDelaySeconds: 0
            failureThreshold: 24
            periodSeconds: 5
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
            - name: dind-externals
              mountPath: /home/runner/externals
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
            - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
              value: "120"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
      volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
