kube-prometheus-stack:
  crds:
    enabled: true
  defaultRules:
    create: false
  global:
    rbac:
      create: true
    imageRegistry: ""
  alertmanager:
    enabled: false
  grafana:
    enabled: true
  kubernetesServiceMonitors:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: true
  coreDns:
    enabled: true
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      "node-role.kubernetes.io/control-plane": ""
  prometheus:
    prometheusSpec:
      replicas: 1
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      storageSpec: {}
      retention: 7d
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: Exists
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
    ingress:
      enabled: false
