name: Release Base Image

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  generate_release_artifacts:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: release-session
      - name: Get Output
        run: |
          terraform init
          echo "$(terraform output -raw disk_image_url)"
          wget -c  $(terraform output -raw disk_image_url)
        working-directory: ./terraform/bootstrap/cluster
      - name: Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          working_directory: ./terraform/bootstrap/cluster
          files: metal-arm64.raw.xz
